apiVersion : apps/v1
kind: Deployment
metadata:
  name: javaapp
  labels:
    app: javaapp
spec:
  selector:
    matchLabels:
      app: javaapp
  replicas: 1
  template:
    metadata:
      labels:
        app: javaapp 
    spec:
      containers:
        - name: rdtechiepipelinesjavascriptdocker 
          image: bschubacr.azurecr.io/rdtechiepipelinesjavascriptdocker
          ports:
          - containerPort: 8080
