apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: rdtechiepipelinesjavascriptdocker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rdtechiepipelinesjavascriptdocker 
    spec:
      containers:
        - name: rdtechiepipelinesjavascriptdocker 
          image: bschubacr.azurecr.io/rdtechiepipelinesjavascriptdocker
          ports:
          - containerPort: 8080